### PR TITLE
Implemented settings file.

### PR DESCRIPTION
**Pull request by slatian**
Now it works on my machine too, thank you for crating this!

Also Added a link to the kosit xrechung-testsuite in the README so one can get a valid XRechung file for trying it out.

### CODE REVIEW

**Comment by dragotin** [comment]
Thanks for your PR! 

Can you elaborate what the problem exactly is on your machine? Are you running on Windows? I fear your PR breaks now *my* system, so we have to elaborate a bit ;-)

**Comment by slatian** [comment]
> Can you elaborate what the problem exactly is on your machine?

https://github.com/dragotin/xrechnung/blob/8a02237ea9f840686e7d02aea1a76b6044c7f4ad/xrview/xrechnung.h#L59 Your saxon paths are hardcoded … and (usually uses GTK guy here :wink: ) there is no obvious way they get read from a configuration file. 

Also I managed to mess up the new READMEm
I changed the extension of the configuration file to be a `.ini` file to match the parsers name (`.conf`, in my head at least hints a some wired custom format is used.)

> Are you running on Windows?

Windows? If by that you mean Wayland surfaces with some decoration around them … yes.

> I fear your PR breaks now my system

Apologies. I'm testing on Voidlinux and Debian on the relevant machines, but I have not found all of the dependencies for Debian yet. Make sure you have the config file in the new place (lowercase paths because that makes it less easy to mess up.)

**Comment by dragotin** [comment]
Thanks again, I got confused, but it was my fault: I forgot to commit changes that I had locally with the QSettings addition. I did that now, and added your suggestions as applicable. 

As a result, I am closing this PR, because it is just not needed any more. But thank you very much for your work and pointing out the flaws.

Details:
- I kept the config file name extension with `.config` because that is the default by Qt.

**Comment by slatian** [comment]
No problem, Thank you for the improvements!

**Pull request closed without merging**
